version: '2'
services:
  website:
    restart: unless-stopped
    container_name: target2
    build: ./
    ports:
      - "80:80"
      - "3222:22"
    depends_on:
      - db
  db:
    restart: unless-stopped
    image: mariadb:10.1
    container_name: db
    volumes:
      - ./configs:/tmp/configs
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql_is_secure
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
      MYSQL_DATABASE: bricks