<?php
# This file was automatically generated by the Bricks installer. 
# If you make manual changes, please keep track in case you need to recreate them later.

$dbuser = 'app_user'; //MySQL database username
$dbpass = 'app_pass'; //MySQL database password
$dbname = 'bricks';  //MySQL database name
$host = 'db';  //MySQL database host
$showhint = true;  //Shows the last executed SQL query
$server = 'http://'.$_SERVER['SERVER_ADDR'];  //The protocol and server name to use in fully-qualified URLs
$scriptpath = '/release-channel';
?>